In [16]:
%load_ext jupyter_black

In [2]:
import numpy as np

In [3]:
x = np.linspace(
    -129.995,
    -60.005002000040975,
    7000,
    dtype=np.float32,
)
y = np.linspace(
    54.995,
    20.005000000002696,
    2500,
    dtype=np.float32,
)
x

array([-129.995   , -129.985   , -129.975   , ...,  -60.025   ,
        -60.015003,  -60.005   ], dtype=float32)

In [12]:
idx = np.argmin(abs(x[:,np.newaxis]- np.array([-100, -90])),axis=0)
idx

array([2999, 4000])

In [19]:
x[idx]

array([-100.005,  -89.995], dtype=float32)

In [23]:
delta = abs(x[:, np.newaxis] - np.array([-100, -90]))
x[np.argmin(delta, axis=0)]

array([-100.005,  -89.995], dtype=float32)